development:
  adapter: postgresql
  database: crb_jobs
  username: crb
  password:
  host: localhost
  pool: 20
  wait_timeout: 20
  reconnect: true

test:
  adapter: postgresql
  database: crb_jobs_test
  username: crb
  password:
  host: localhost
  pool: 20
  wait_timeout: 20
  reconnect: true

production:
  adapter: postgresql
  database: crb_jobs
  username: crb
  password:
  host: localhost
  pool: 20
  wait_timeout: 20
  reconnect: true

