development:
  adapter: postgresql
  database: crb_jobs
  username: crb
  password:
  host: localhost
  pool: 20
  wait_timeout: 20
  reconnect: true

test:
  adapter: postgresql
  database: crb_jobs_test
  username: crb
  password:
  host: localhost
  pool: 20
  wait_timeout: 20
  reconnect: true

production:
  adapter: postgresql
  database: db
  username: root
  password: 7UTOtz9xe9emmuw7
  host: 172.17.42.1
  port: 49155
  pool: 20
  wait_timeout: 20
  reconnect: true

